name: Auto Translate Docs
on:
  push:
    paths:
      - 'docs/en/**/*.md'
      - 'docs/it/**/*.md'
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            docs/en/**/*.md
            docs/it/**/*.md

      - name: Translate EN → IT
        if: contains(steps.changes.outputs.all_changed_files, 'docs/en/')
        run: |
          python scripts/translate.py en it

      - name: Translate IT → EN
        if: contains(steps.changes.outputs.all_changed_files, 'docs/it/')
        run: |
          python scripts/translate.py it en

      - name: Commit & Push translations
        run: |
          git config user.name "roundtable-bot"
          git config user.email "bot@roundtable.org"
          git add docs/
          git commit -m "Auto-translate updated docs"
          git push
