name: Translate Markdown Docs - Auto (Modified Only)

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**.md'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install googletrans==4.0.0-rc1

      - name: Get modified Markdown files
        id: modified_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '\.md$' || echo '')"

      - name: Translate only modified files
        if: steps.modified_files.outputs.files != ''
        run: |
          for f in ${{ steps.modified_files.outputs.files }}; do
            echo "Translating $f..."
            python scripts/translate_md_auto.py $f
          done

      - name: Commit and push translated docs
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: 'Roundtable Bot'
          author_email: 'roundtable-bot@example.com'
          message: 'Auto-update translated Markdown docs (modified only)'
          add: 'docs/**'
